name: Pull request checks
on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened, edited]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v2

      - run: pnpm install
      - run: pnpm exec eslint .

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v2

      - run: pnpm install
      - run: pnpm exec prettier --check .

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v2

      - run: pnpm install
      - run: pnpm exec svelte-kit sync
      - run: pnpm exec svelte-check --tsconfig ./jsconfig.json
